### ISSUE TITLE
Create Figma Mockup

### ISSUE THREAD

**Issue by Chizaram-Igolo** [emmanuelonwukwe/secure-vote#2]

**Comment by gabbyedgar** [comment]
I am working on this!

**Comment by Chizaram-Igolo** [comment]
> I am working on this! 

When you're done with a screen, you may create a folder; `/mockup`, at the root of the project and place the `.fig` and `.png` files in there. 

For example: 

```
├── mockup
│   ├── screen_01.fig
│   ├── screen_01.png
├── public
├── src
├── .eslintrc.cjs
├── .gitignore
├── README.md
├── index.html
├── package-lock.json
├── package.json 
└── vite.config.js
``` 

Your commit message may look like this: 

`📐✏️ docs(mockup): Create Figma Mockup (#2)`

**Comment by gabbyedgar** [comment]
Done
